name: dak
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-176.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.0.0
  firebase_core: ^2.31.1
  provider: ^6.1.2
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/google-cloud-key.json
